apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui
  labels:
    app: frontend
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
  template:
    metadata:
      labels:
        app: frontend
        tier: app
    spec:
      containers:
      - name: karsajobs-frontend
        image: teguhy2910/karsajobs-ui:latest
        ports:
          - containerPort: 8000
        env:
          - name: APP_PORT
            value: "8000"
